### ISSUE TITLE
rack update fails if resource_class is set

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#31]
When updating a rack and resource class is set, I get following error:
2013-07-18 10:59:33.109 24805 INFO sqlalchemy.engine.base.Engine [-](1,)
2013-07-18 10:59:33.111 24805 ERROR tuskar.api.controllers.v1 [-] Parent instance <Rack at 0x3d80450> is not bound to a Session; lazy load operation of attribute 'resource_class' cannot proceed
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1 Traceback (most recent call last):
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/api/controllers/v1.py", line 268, in put
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     result = pecan.request.dbapi.update_rack(rack_id, rack)
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/db/sqlalchemy/api.py", line 215, in update_rack
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     rack.resource_class = rc
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     instance_dict(instance), value, None)
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 683, in set
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     old = self.get(state, dict_, passive=PASSIVE_NO_FETCH)
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 453, in get
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     value = self.callable_(state, passive)
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 481, in _load_for_state
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1     (mapperutil.state_str(state), self.key)
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1 DetachedInstanceError: Parent instance <Rack at 0x3d80450> is not bound to a Session; lazy load operation of attribute 'resource_class' cannot proceed
2013-07-18 10:59:33.111 24805 TRACE tuskar.api.controllers.v1 
2013-07-18 10:59:33.113 24805 WARNING wsme.api [-] Client-side error: Invalid data
localhost.localdomain - - [18/Jul/2013 10:59:33] "PUT /v1/racks/1 HTTP/1.1" 400 127547

I pass following params to tuskar client lib:
(Pdb) p params
{'slots': 0, 'subnet': u'192.168.1.0/24', 'nodes': [], 'name': u'rack1', 'resource_class': {'id': u'1'}}
(Pdb) tuskarclient(request).racks.update(rack_id, **params)

But Jirka Stransky tested directly through curl and the issue is same (not on tuskarclient side).

**Comment by mfojtik** [comment]
@jprovaznik can you please confirm that this issues is fixed?

**Comment by jprovaznik** [comment]
yes, rack update now works fine.
