### ISSUE TITLE
loading sample.data fails

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#63]
with current master, when loading sample.data it fails with following error:
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"flavors": [{"capacities": [{"unit": "count", "value": "4", "name": "cpu"}, {"unit": "GB", "value": "15", "name": "memory"}, {"unit": "GB", "value": "1680", "name": "storage"}], "name": "m1.xlarge"}], "service_type": "compute", "racks": [{"id": 1, "links": [{"href": "http://localhost:6385/v1/racks/1", "rel": "self"}]}, {"id": 2, "links": [{"href": "http://localhost:6385/v1/racks/2", "rel": "self"}]}], "name": "compute-rc"}' http://localhost:6385/v1/resource_classes
Request returned failure/redirect status.
Traceback (most recent call last):
  File "tools/sample_data.py", line 230, in <module>
    generate_data()
  File "tools/sample_data.py", line 220, in generate_data
    flavors=[flavors[3]])
  File "tools/sample_data.py", line 115, in create_resource_class
    racks=racks, flavors=flavors))
  File "tools/sample_data.py", line 96, in json_request
    resp, body = http_request(conn, base_url, url, method, **kwargs)
  File "tools/sample_data.py", line 79, in http_request
    raise RuntimeError('Status code %d returned' % resp.status)
RuntimeError: Status code 400 returned

**Comment by mfojtik** [comment]
I get this error in Tuskar log:

```
2013-07-24 14:45:27.324 15251 TRACE tuskar.api.controllers.v1 ClientException: Instance Type with name compute-rc.m1.xlarge already exists. (HTTP 409) (Request-ID: req-026207ff-bdec-4c99-a7aa-54fc743db975)
2013-07-24 14:45:27.324 15251 TRACE tuskar.api.controllers.v1 
2013-07-24 14:45:27.327 15251 WARNING wsme.api [-] Client-side error: Invalid data
```

(tested on **empty** database)

**Comment by marios** [comment]
yeah, this is a synchronization issue. we are all using the same sample_data and for each resource class the flavors are all being created in nova. the same nova setup. as flavor names are determined by rc.name+flav.name (like m1.small) we get errors because 'flavor already exists'. not sure how to deal with this

**Comment by marios** [comment]
should be addressed by https://github.com/tuskar/tuskar/pull/69

**Comment by jprovaznik** [comment]
PR #69 fixes this issue
