### ISSUE TITLE
flavor deletion

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#64]
When deleting a flavor:
$ curl -i -X GET -H 'Content-Type: application/octet-stream' -H 'User-Agent: python-tuskarclient' http://127.0.0.1:6385/v1/resource_classes/3/flavorsHTTP/1.0 200 OK
Date: Wed, 24 Jul 2013 13:10:01 GMT
Server: WSGIServer/0.1 Python/2.7.3
Content-Length: 407
Content-Type: application/json; charset=UTF-8

[{"capacities": [{"value": "1", "name": "vcpu", "unit": ""}, {"value": "64", "name": "ram", "unit": "MB"}, {"value": "0", "name": "root_disk", "unit": "GB"}, {"value": "0", "name": "ephemeral_disk", "unit": "GB"}, {"value": "0", "name": "swap_disk", "unit": "MB"}], "max_vms": null, "id": 3, "links": [{"href": "http://127.0.0.1:6385/v1/resource_classes/3/flavors/3", "rel": "self"}], "name": "asdf1.nano"}]
$ curl -i -X DELETE -H 'Content-Type: application/octet-stream' -H 'User-Agent: python-tuskarclient' http://127.0.0.1:6385/v1/resource_classes/3/flavors/3

I get this error in server log:
2013-07-24 15:10:21.618 23344 ERROR wsme.api [-] Server-side error: "Flavor None could not be found. (HTTP 404) (Request-ID: req-173c9d3d-78cd-4c9d-8992-6e9d3e2ea763)". Detail: 
Traceback (most recent call last):

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsmeext/pecan.py", line 70, in callfunction
    result = f(self, _args, *_kwargs)

  File "/home/jprovazn/devel/tuskar/tuskar/api/controllers/v1.py", line 392, in delete
    self.nova.delete_flavor(nova_flavor_uuid)

  File "/home/jprovazn/devel/tuskar/tuskar/compute/nova.py", line 71, in delete_flavor
    self.nova_client.flavors.delete(nova_flavor_id)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/v1_1/flavors.py", line 106, in delete
    self._delete("/flavors/%s" % base.getid(flavor))

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/base.py", line 154, in _delete
    _resp, _body = self.api.client.delete(url)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/client.py", line 239, in delete
    return self._cs_request(url, 'DELETE', **kwargs)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/client.py", line 217, in _cs_request
    **kwargs)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/client.py", line 199, in _time_request
    resp, body = self.request(url, method, **kwargs)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/client.py", line 193, in request
    raise exceptions.from_response(resp, body, url, method)

NotFound: Flavor None could not be found. (HTTP 404) (Request-ID: req-173c9d3d-78cd-4c9d-8992-6e9d3e2ea763)

localhost.localdomain - - [24/Jul/2013 15:10:21] "DELETE /v1/resource_classes/3/flavors/3 HTTP/1.1" 400 127422

**Comment by marios** [comment]
again, this is a sync issue - we are all pointing at the same nova setup. we need to work this out, but possibly post demo

**Comment by jguiditta** [comment]
can we just set a flag somewhere whether to hit a real nova setup or not?  this is a similar problem to always hitting a real (internal) heat instance

**Comment by mfojtik** [comment]
@jguiditta the 'hitting internal Heat instance' problem is now fixed... even if you don't have Heat setup and running, you should be able to operate on Rack normally... You will just notice some errors in the log, but Tuskar should behave as usual.

We call to Heat API because of the Rack state update... So if you don't have Heat setup and you hit the 'big red button' (tm), you will not get the Heat status updated for Rack.state :-)

**Comment by marios** [comment]
should be addressed in https://github.com/tuskar/tuskar/pull/69

**Comment by jprovaznik** [comment]
With PR #69 it works for me, closing.
