### ISSUE TITLE
Can't create a flavor

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#68]
When adding new flavor to a resource class:
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'User-Agent: python-tuskarclient' -d '{"max_vms": "2", "capacities": [{"unit": "", "name": "vcpu", "value": "4"}, {"unit": "MB", "name": "ram", "value": "8192"}, {"unit": "GB", "name": "root_disk", "value": "80"}, {"unit": "GB", "name": "ephemeral_disk", "value": "0"}, {"unit": "MB", "name": "swap_disk", "value": "0"}], "name": "rc1.large"}' http://127.0.0.1:6385/v1/resource_classes/3/flavors

The request fails with following error in tuskar.log:
2013-07-25 08:55:08.207 10253 INFO sqlalchemy.engine.base.Engine [-](u'3',)
2013-07-25 08:55:08.210 10253 ERROR tuskar.api.controllers.v1 [-] Ram must be an integer.
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1 Traceback (most recent call last):
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/api/controllers/v1.py", line 348, in post
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1     pecan.request.dbapi.get_resource_class(resource_class_id).name)
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/compute/nova.py", line 63, in create_flavor
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1     nova_flavor = self.nova_client.flavors.create(name, ram, cpu, disk)
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/novaclient/v1_1/flavors.py", line 128, in create
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1     raise exceptions.CommandError("Ram must be an integer.")
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1 CommandError: Ram must be an integer.
2013-07-25 08:55:08.210 10253 TRACE tuskar.api.controllers.v1 
2013-07-25 08:55:08.212 10253 WARNING wsme.api [-] Client-side error: Invalid data
localhost.localdomain - - [25/Jul/2013 08:55:08] "POST /v1/resource_classes/3/flavors HTTP/1.1" 400 127566

If I send integer for ram value, I get this error in tuskar log:
2013-07-25 08:54:38.950 10253 ERROR wsme.api [-] Server-side error: "value: Wrong type. Expected '<type 'unicode'>', got '<type 'int'>'". Detail: 
Traceback (most recent call last):

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsmeext/pecan.py", line 66, in callfunction
    pecan.request.body, pecan.request.content_type

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/args.py", line 269, in get_args
    from_body = args_from_body(funcdef, body, mimetype)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/args.py", line 216, in args_from_body
    body, datatypes, bodyarg=funcdef.body_type is not None

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/json.py", line 213, in parse
    kw = {argname: fromjson(datatypes[argname], jdata)}

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/simplegeneric.py", line 63, in dispatch
    return f(_args, *_kw)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/json.py", line 137, in fromjson
    fromjson(attrdef.datatype, value[attrdef.name]))

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/simplegeneric.py", line 63, in dispatch
    return f(_args, *_kw)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/json.py", line 149, in array_fromjson
    return [fromjson(datatype.item_type, item) for item in value]

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/simplegeneric.py", line 63, in dispatch
    return f(_args, *_kw)

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/rest/json.py", line 137, in fromjson
    fromjson(attrdef.datatype, value[attrdef.name]))

  File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/wsme/types.py", line 345, in **set**
    raise ValueError("%s: %s" % (self.name, e))

ValueError: value: Wrong type. Expected 'type 'unicode>', got 'type 'int''

localhost.localdomain - - [25/Jul/2013 08:54:38] "POST /v1/resource_classes/3/flavors HTTP/1.1" 400 127566

**Comment by marios** [comment]
yes you can - in your request above you are using 'ram' and 'root_disk' whereas right now we have defined 'memory' and 'storage' for flavors. I understand that in future we can and should enhance the model to include root_storage, swap_disk etc but I don't see this as a priority for the demo, IMO.

Doing:

```
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'User-Agent: python-tuskarclient' -d '{"max_vms": "2", "capacities": [{"unit": "", "name": "cpu", "value": "4"}, {"unit": "MB", "name": "memory", "value": "8192"}, {"unit": "GB", "name": "storage", "value": "80"}, {"unit": "GB", "name": "ephemeral_disk", "value": "0"}, {"unit": "MB", "name": "swap_disk", "value": "0"}], "name": "rc1.large"}' http://127.0.0.1:6385/v1/resource_classes/2/flavors


HTTP/1.0 201 Created
Date: Thu, 25 Jul 2013 07:12:03 GMT
Server: WSGIServer/0.1 Python/2.7.3
Content-Length: 404
Content-Type: application/json; charset=UTF-8

{"capacities": [{"value": "4", "name": "cpu", "unit": ""}, {"value": "8192", "name": "memory", "unit": "MB"}, {"value": "80", "name": "storage", "unit": "GB"}, {"value": "0", "name": "ephemeral_disk", "unit": "GB"}, {"value": "0", "name": "swap_disk", "unit": "MB"}], "max_vms": 2, "id": 2, "links": [{"href": "http://127.0.0.1:6385/v1/resource_classes/2/flavors/2", "rel": "self"}], "name": "rc1.large"}[m@m tuskar]$ 
```

If you agree please close out the ticket

**Comment by jprovaznik** [comment]
OK, thanks for info, will update UI accordingly.
